import type { IndustryContent } from "@/components/public/templates/industryPage";

export const INDUSTRIES: Record<string, IndustryContent> = {
  education: {
    slug: "education",
    name: "Education",
    noun: "education",
    heroImage: "/images/unsplash/photo-1503676260728-1c00da094a0b-1600.webp",
    headline: "Education platforms, engineered for [[the academic calendar.]]",
    lede: "K-12 districts through research universities. Platforms scaled for enrollment peaks, FERPA-aligned, and operated against SLOs — [[not war rooms.]]",
    pills: ["K-12 and higher ed", "FERPA-aligned", "SIS and LMS"],
    narrative: {
      eyebrow: "Education",
      title: "Instruction continues. The platform [[has to keep up.]]",
      kicker: "Enrollment windows, finals, registration — the same systems carry 10× load on the same day, every term.",
      lede: "Student-data sensitivity, identity sprawl across SIS and LMS, and seasonal load patterns are not inconveniences — they are the design constraints. IntraStack builds education platforms against those realities — [[before adding a single feature.]]",
      pillars: [
        { title: "Identity, federated", body: "One directory for faculty, students, parents, contractors — audit trails that survive [[a state review.]]" },
        { title: "Calendar-aware scale", body: "Capacity modeled against registration and finals — not against [[an average day.]]" },
        { title: "Privacy by design", body: "FERPA, COPPA, and state privacy controls embedded in the pipeline — [[not retrofitted after.]]" },
        { title: "Instructional continuity", body: "Change windows respect class schedules — release cadence matches [[the academic term.]]" },
      ],
      closing: "We do not modernize education technology for its own sake — we modernize it for [[the next class.]]",
    },
    challenges: [
      { letter: "A", title: "Seasonal load spikes", body: "Enrollment, finals, registration — the same systems carry 10× load on the same day, every term." },
      { letter: "B", title: "Identity sprawl across SIS and LMS", body: "Faculty, students, parents, contractors. Too many directories. Audit trails fragmented across systems." },
      { letter: "C", title: "Data privacy and compliance", body: "FERPA, COPPA, state privacy laws. Controls that audit cleanly without slowing instruction down." },
    ],
    approach: [
      { title: "Assess current estate", body: "Inventory SIS, LMS, identity, network. Map gaps against sector benchmarks and regulatory exposure." },
      { title: "Stand up landing zones", body: "Multi-account topology · IAM baseline · network segmentation · guardrails for student data." },
      { title: "Migrate and modernize", body: "Critical applications lifted in waves. Workloads that buckle at peak refactored against measured demand." },
      { title: "Operate as one team", body: "Embedded SRE through registration season. Clean capability transfer after." },
    ],
    diagramLabel: "Identity at the front. Campus and cloud workloads in the middle. Observability and cost visible from the SIS owner's desk.",
    related: [
      { kind: "Service", name: "DevOps & Automation", href: "/services/devops_automation" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Service", name: "Staffing Services", href: "/services/staff_augmentation" },
    ],
  },
  finance: {
    slug: "finance",
    name: "Finance",
    noun: "financial services",
    heroImage: "/images/unsplash/photo-1454165804606-c3d57bc86b40-1600.webp",
    headline: "Financial services infrastructure, engineered to [[the regulator’s standard.]]",
    lede: "Tier-1 banks, payments, and capital markets. Delivery inside change windows that do not move, audit trails that do not blink, and [[sub-millisecond on the trading path.]]",
    pills: ["Tier-1 banks", "PCI-DSS", "SOX", "FINRA"],
    narrative: {
      eyebrow: "Financial Services",
      title: "Markets open whether the deploy [[worked or not.]]",
      kicker: "Releases land in 2-hour windows. Rollback is measured in seconds. Auditors want proof, not promises.",
      lede: "Core banking modernization without disrupting 24/7 transaction availability is not a slogan — it is the engagement model. IntraStack embeds inside change-management reality, with real-time fraud, zero-downtime migration, and PCI-DSS evidence [[falling out of the pipeline.]]",
      pillars: [
        { title: "Zero-downtime migration", body: "Strangler patterns around the mainframe, parallel-run validated before [[any cutover.]]" },
        { title: "Real-time risk", body: "Kafka pipelines and ML fraud models tuned against [[live transaction streams.]]" },
        { title: "Audit-grade evidence", body: "SOX, PCI-DSS, and FINRA controls instrumented in CI — not [[attached after the fact.]]" },
        { title: "Latency that pays", body: "Single-digit milliseconds on trading, double-digit on customer paths — both, [[every day.]]" },
      ],
      closing: "The trading floor does not pause for our roadmap — so our roadmap is built around [[the trading floor.]]",
    },
    challenges: [
      { letter: "A", title: "Change windows that do not flex", body: "Markets open whether the deploy worked or not. Releases land in 2-hour windows. Rollback is measured in seconds." },
      { letter: "B", title: "Audit evidence on demand", body: "SOX, PCI, FINRA. Auditors want proof — not promises. Evidence falls out of the pipeline." },
      { letter: "C", title: "Latency that pays the bills", body: "Single-digit milliseconds on the trading path. Double-digit on the customer path. Both. Every day." },
    ],
    approach: [
      { title: "Assess current estate", body: "Trading, payments, core banking, data. Mapped by criticality and regulatory exposure." },
      { title: "Stand up landing zones", body: "Segregated environments · network isolation · evidence pipeline live from day one." },
      { title: "Migrate and modernize", body: "Strangler patterns around the mainframe. Parallel-run validated before any cutover." },
      { title: "Operate as one team", body: "Follow-the-sun rotation through market hours. On-call accountability stays with us." },
    ],
    diagramLabel: "Trading path on one side. Audit and evidence on the other. Every flow labeled, encrypted, and traceable to a control.",
    related: [
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Solution", name: "Enterprise Security", href: "/solutions/enterprise_security" },
      { kind: "Service", name: "Cybersecurity", href: "/services/cybersecurity" },
      { kind: "Solution", name: "Business Continuity", href: "/solutions/business_continuity" },
    ],
  },
  government: {
    slug: "government",
    name: "Government",
    noun: "public sector",
    heroImage: "/images/unsplash/photo-1541872703-74c5e44368f9-1600.webp",
    headline: "Public sector modernization, delivered inside [[procurement reality.]]",
    lede: "Federal, state, and local. FedRAMP, StateRAMP, CMMC, CJIS. Accessibility built in, ATO timelines compressed by automation, [[vendor lock-out avoided by design.]]",
    pills: ["FedRAMP", "StateRAMP", "CMMC", "Section 508"],
    narrative: {
      eyebrow: "Government & Public Sector",
      title: "Authorization is not an afterthought — it is [[the architecture.]]",
      kicker: "FedRAMP boundaries, CUI handling, and Section 508 are design inputs, not paperwork.",
      lede: "Public sector modernization fails when the authorization boundary, the procurement vehicle, and the engineering plan are designed in isolation. IntraStack delivers FedRAMP-aligned environments, CMMC 2.0 readiness, and DevSecOps adoption — with evidence pipelines instrumented [[from day one.]]",
      pillars: [
        { title: "ATO acceleration", body: "Continuous monitoring and control evidence automated — months of paperwork [[compressed to weeks.]]" },
        { title: "CUI by design", body: "Boundary, identity, and key management aligned to NIST 800-171 — not [[bolted on later.]]" },
        { title: "Accessibility from CI", body: "Section 508 and WCAG 2.1 AA gates fail the build, not [[the audit.]]" },
        { title: "Cleared continuity", body: "Cleared engineers, cleared documentation, runbooks the IG can [[read end to end.]]" },
      ],
      closing: "Public services should be modernized at the speed of citizen need — not at the speed of [[the legacy SOW.]]",
    },
    challenges: [
      { letter: "A", title: "Procurement gravity", body: "Vehicles, schedules, set-asides. The contracting path shapes the architecture as much as the requirements do." },
      { letter: "B", title: "Authority to Operate", body: "FedRAMP, ATO packages, continuous monitoring. Months of paperwork — unless it is automated." },
      { letter: "C", title: "Accessibility is law, not preference", body: "Section 508 and WCAG 2.1 AA on day one. Retrofitting is the expensive path." },
    ],
    approach: [
      { title: "Assess current estate", body: "Systems-of-record · authorization boundary · ATO status per system." },
      { title: "Stand up landing zones", body: "FedRAMP-aligned environment · evidence pipeline · accessibility gates in CI." },
      { title: "Migrate and modernize", body: "ATO scope reduced as work proceeds. Systems that do not earn their keep are retired." },
      { title: "Operate as one team", body: "Cleared engineers · cleared documentation · runbooks the inspector general can read." },
    ],
    diagramLabel: "Authorization boundary on the perimeter. Continuous monitoring threaded through. Public-facing services accessible by default.",
    related: [
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Service", name: "Cloud Migration", href: "/services/cloud_migration" },
      { kind: "Service", name: "Cloud Strategy & Design", href: "/services/it_consulting" },
    ],
  },
  healthcare: {
    slug: "healthcare",
    name: "Healthcare",
    noun: "healthcare",
    heroImage: "/images/unsplash/photo-1576091160550-2173dba999ef-1600.webp",
    headline: "Healthcare platforms, HIPAA-aligned and [[clinician-first.]]",
    lede: "Payers, providers, and digital health. Integration with the EHR — not against it. PHI governed in pipeline. Workflows engineered against [[clinical reality.]]",
    pills: ["HIPAA", "HITRUST", "FHIR and HL7", "EHR-integrated"],
    narrative: {
      eyebrow: "Healthcare & Life Sciences",
      title: "Care coordination, [[engineered.]]",
      kicker: "Legacy EHRs create interoperability barriers. PHI governance is non-negotiable. Every click added is a click clinicians refuse.",
      lede: "Interoperability barriers, clinical data silos, and PHI governance complexity are not technical inconveniences — they are the strategic risk surface. IntraStack delivers HL7 FHIR APIs, clinical data lakes, and HIPAA audit readiness, embedded against [[the realities of care delivery.]]",
      pillars: [
        { title: "EHR-integrated, not adjacent", body: "Epic, Cerner, Meditech — FHIR-first interfaces with safe HL7 v2 [[parallel run.]]" },
        { title: "PHI that travels safely", body: "Encryption, key management, BAAs, minimum-necessary access — audited [[across vendor boundaries.]]" },
        { title: "Clinical workflow priority", body: "If a release adds a click, it does not ship — workflows beat [[features, every release.]]" },
        { title: "Population health analytics", body: "Clinical data lakes that survive scrutiny from informatics, compliance, and [[the board.]]" },
      ],
      closing: "Technology has no business in care delivery unless it makes the next visit [[safer or faster.]]",
    },
    challenges: [
      { letter: "A", title: "Integration with the EHR", body: "Epic, Cerner, Meditech. Every shop different. Every connection consequential. FHIR is the target. HL7 v2 is the reality." },
      { letter: "B", title: "PHI that travels safely", body: "Encryption, key management, BAAs, minimum necessary access. Controls that audit cleanly across vendor boundaries." },
      { letter: "C", title: "Clinician experience", body: "If it adds a click, it does not ship. Workflows beat features. Every release." },
    ],
    approach: [
      { title: "Assess current estate", body: "Data flows · BAAs · integration points · clinical workflows mapped." },
      { title: "Stand up landing zones", body: "HIPAA-aligned environment · key management · minimum-necessary access." },
      { title: "Migrate and modernize", body: "FHIR-first interfaces. Safe parallel run with existing HL7 pipes before cutover." },
      { title: "Operate as one team", body: "On-call coverage matched to clinical hours. Weekly review with informatics leadership." },
    ],
    diagramLabel: "EHR on the left. Patient services on the right. PHI flows encrypted, logged, and minimum-necessary throughout.",
    related: [
      { kind: "Solution", name: "Security & Compliance", href: "/solutions/security_compliance" },
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Service", name: "AI & Machine Learning", href: "/services/ai_engineering" },
      { kind: "Service", name: "Software Development", href: "/services/software_development" },
    ],
  },
  logistics: {
    slug: "logistics",
    name: "Logistics",
    noun: "logistics and supply chain",
    heroImage: "/images/unsplash/photo-1586528116311-ad8dd3c8310d-1600.webp",
    headline: "Logistics platforms, real-time and [[decision-ready.]]",
    lede: "Carriers, 3PLs, and shippers. Telemetry at the edge, optimization in the cloud, dashboards in the dispatcher’s hand — [[and the driver’s cab.]]",
    pills: ["Real-time fleet", "TMS and WMS", "Edge telemetry"],
    narrative: {
      eyebrow: "Logistics & Supply Chain",
      title: "OT and IT convergence, [[done once.]]",
      kicker: "Trucks lose signal. Yards lose power. The platform survives both — or it loses customers.",
      lede: "Edge fragmentation, EDI sprawl across every shipper relationship, and real-time optimization that has to reach the driver before the next stop are the operational truth. IntraStack delivers predictive maintenance, fleet optimization, and a canonical event model that holds [[under measured load.]]",
      pillars: [
        { title: "Edge that survives", body: "Local-first telemetry and ingest that tolerates disconnection — without [[silent data loss.]]" },
        { title: "EDI as a platform", body: "Customer integrations expressed as configuration — not [[a one-off per partner.]]" },
        { title: "Streaming optimization", body: "Routing, slotting, and ETA decisions delivered before [[the next stop.]]" },
        { title: "Peak-week operations", body: "Holiday and quarter-end run jointly — accountability stays with [[one team.]]" },
      ],
      closing: "Optimization that does not reach the driver is a slide deck — not [[a logistics platform.]]",
    },
    challenges: [
      { letter: "A", title: "Edge that disconnects", body: "Trucks lose signal. Yards lose power. Platforms that cannot survive that lose customers." },
      { letter: "B", title: "TMS and WMS integration sprawl", body: "Every customer requires a different EDI flavor and a different label format. Integration cannot be a one-off per partner." },
      { letter: "C", title: "Optimization in real time", body: "Routing, slotting, ETA. Useful only if the decision reaches the driver before the next stop." },
    ],
    approach: [
      { title: "Assess current estate", body: "Fleet telemetry · TMS / WMS · EDI flows · customer integrations." },
      { title: "Stand up landing zones", body: "Edge fabric · real-time ingestion · canonical event model." },
      { title: "Migrate and modernize", body: "Streaming-first analytics. ML routing layered against measured demand." },
      { title: "Operate as one team", body: "24/7 operations cover. Holiday peak war-room run jointly." },
    ],
    diagramLabel: "Telemetry at the edge. Streaming ingest in the middle. Decisions and dashboards out to dispatchers and drivers.",
    related: [
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Solution", name: "AI Automation", href: "/solutions/ai_automation" },
      { kind: "Service", name: "Software Development", href: "/services/software_development" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
    ],
  },
  manufacturing: {
    slug: "manufacturing",
    name: "Manufacturing",
    noun: "manufacturing",
    heroImage: "/images/unsplash/photo-1565793298595-6a879b1d9492-1600.webp",
    headline: "OT and IT, engineered to [[one architecture.]]",
    lede: "Industrial IoT, MES, ERP, and the analytics layer that connects them. Plant-floor reality respected. Boardroom dashboards [[aligned to it.]]",
    pills: ["Industrial IoT", "MES and ERP", "OT/IT bridge"],
    narrative: {
      eyebrow: "Manufacturing & Industrial",
      title: "Downtime is the only [[KPI that wins.]]",
      kicker: "Plant systems and IT systems do not share vocabulary or risk tolerance. The architecture has to respect both.",
      lede: "Legacy protocols meeting cloud-native expectations, OT/IT divides, and zero tolerance for line stoppages are the operating environment. IntraStack engineers the bridge — Modbus, OPC UA, MQTT, and MES under one observable layer with [[measured downtime as the scoreboard.]]",
      pillars: [
        { title: "Edge gateway pattern", body: "OPC UA layer that speaks plant protocols and cloud APIs — without [[double translation.]]" },
        { title: "Predictive maintenance", body: "IoT models tuned against measured failure modes — not [[a reference architecture.]]" },
        { title: "OT-aware change", body: "Release windows respect production schedules — change advisory boards [[stay informed.]]" },
        { title: "ERP and MES alignment", body: "Plant-floor signals reach the boardroom dashboard — by [[design, not by export.]]" },
      ],
      closing: "Every roadmap loses to the line going down — so resilience comes first, and features come [[after that.]]",
    },
    challenges: [
      { letter: "A", title: "OT and IT divide", body: "Plant systems and IT systems do not share vocabulary or risk tolerance. The architecture must respect both." },
      { letter: "B", title: "Legacy protocols meet the cloud", body: "Modbus, Profinet, OPC UA, MQTT. All under one roof. None retiring soon." },
      { letter: "C", title: "Downtime is the only KPI", body: "Every roadmap loses to the line going down. Resilience first. Features second." },
    ],
    approach: [
      { title: "Assess current estate", body: "Plant systems · OT network · MES · ERP · data flows." },
      { title: "Stand up landing zones", body: "Edge gateway pattern · OPC UA layer · cloud analytics environment." },
      { title: "Migrate and modernize", body: "Pilot one line. Prove value against measured downtime. Roll out plant by plant." },
      { title: "Operate as one team", body: "OT-aware on-call. Change windows that respect production." },
    ],
    diagramLabel: "Plant floor on the bottom. OPC UA layer in the middle. ERP, analytics, and AI on top — gated, audited, observable.",
    related: [
      { kind: "Service", name: "AI & Machine Learning", href: "/services/ai_engineering" },
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Service", name: "Cybersecurity", href: "/services/cybersecurity" },
    ],
  },
  retail: {
    slug: "retail",
    name: "Retail",
    noun: "retail",
    heroImage: "/images/unsplash/photo-1481437156560-3205f6a55735-1600.webp",
    headline: "Retail platforms — omnichannel and [[peak-ready.]]",
    lede: "Storefront, mobile, POS, and the warehouse behind them. One inventory truth, one customer view, one team [[holding the pager on Black Friday.]]",
    pills: ["Omnichannel", "Real-time inventory", "Peak-season ready"],
    narrative: {
      eyebrow: "Retail & Consumer Commerce",
      title: "Inventory truth, [[on the product page.]]",
      kicker: "Channel sprawl fragments customer identity. Inventory drift kills the promise. Peak day arrives on the calendar.",
      lede: "Omnichannel inventory fragmentation and customer data silos are the strategic constraint, not a marketing problem. IntraStack delivers real-time inventory platforms, demand forecasting, and customer data consolidation — engineered to hold up [[mid-rush, not just in staging.]]",
      pillars: [
        { title: "One inventory", body: "Network-wide, real-time, accurate enough to promise on [[the product page.]]" },
        { title: "Unified customer", body: "Web, app, store, marketplace — one identity, one carted state, [[one journey.]]" },
        { title: "Peak-day engineering", body: "Capacity, latency, and operations modeled against Black Friday — not [[an average Tuesday.]]" },
        { title: "Composable commerce", body: "Headless front-end, modular back-end — replatform without [[a multi-year freeze.]]" },
      ],
      closing: "If the storefront cannot promise the unit, the rest of the platform is [[expensive theater.]]",
    },
    challenges: [
      { letter: "A", title: "Peak demand on a calendar", body: "Black Friday. Holiday weekends. Drop days. Capacity, latency, and operations all have to land on the same day." },
      { letter: "B", title: "Inventory truth", body: "Real-time. Network-wide. Accurate enough to promise on the product page — mid-rush." },
      { letter: "C", title: "Channel sprawl", body: "Web, application, store, marketplace. One customer. One identity. One carted state." },
    ],
    approach: [
      { title: "Assess current estate", body: "Storefront · OMS · WMS · POS · CDP. Flows and failure modes mapped." },
      { title: "Stand up landing zones", body: "Composable commerce baseline · CDN, identity, and observability live." },
      { title: "Migrate and modernize", body: "Headless front-end · real-time inventory layer · phased channel rollout." },
      { title: "Operate as one team", body: "Peak-season war-room run jointly. Year-round on-call after." },
    ],
    diagramLabel: "Storefront and applications on top. OMS, inventory, and pricing in the middle. Stores and warehouses at the base. One customer view threading through.",
    related: [
      { kind: "Service", name: "Software Development", href: "/services/software_development" },
      { kind: "Solution", name: "Data Analytics", href: "/solutions/data_analytics" },
      { kind: "Service", name: "Mobile Development", href: "/services/mobile_development" },
      { kind: "Solution", name: "AI Automation", href: "/solutions/ai_automation" },
    ],
  },
  telecom: {
    slug: "telecom",
    name: "Telecom",
    noun: "telecom",
    heroImage: "/images/unsplash/photo-1611605698335-8b1569810432-1600.webp",
    headline: "Carrier-grade, without [[the carrier timeline.]]",
    lede: "OSS and BSS modernization. 5G workloads. Cloud-native data plane delivered with telco-grade discipline and [[reliability accountability.]]",
    pills: ["Carrier-grade", "5G ready", "OSS and BSS"],
    narrative: {
      eyebrow: "Telecom & Communications",
      title: "Five-nines is a contract — not [[a slide.]]",
      kicker: "OSS and BSS calcified across decades of customization. Modernization has to happen without freezing the business.",
      lede: "Telecom modernization fails when the OSS/BSS estate, the CNF data plane, and the regulator’s reliability expectations are treated as separate workstreams. IntraStack engineers them as one program — strangler patterns, cloud-native network functions, and evidence pipelines [[under a single SLA.]]",
      pillars: [
        { title: "OSS/BSS strangler", body: "Legacy carved down in working increments — business runs [[the entire time.]]" },
        { title: "Cloud-native CNFs", body: "Low-latency data plane, service mesh, and policy controls engineered for [[carrier reliability.]]" },
        { title: "Five-nines, instrumented", body: "Reliability evidence in CI, on dashboards, and in [[the regulator’s report.]]" },
        { title: "NOC-adjacent operations", body: "Runbooks that match the existing OSS — accountability stays with [[one team.]]" },
      ],
      closing: "Carrier-grade is not a marketing posture — it is a contract with users, regulators, and [[the board.]]",
    },
    challenges: [
      { letter: "A", title: "OSS and BSS that calcified", body: "Decades of customizations. No clean seam. Modernization without freezing the business is the entire game." },
      { letter: "B", title: "Network functions in the cloud", body: "CNFs, service mesh, low-latency data plane. Patterns the average platform team has not delivered." },
      { letter: "C", title: "Reliability with regulatory teeth", body: "Five-nines is not a slide. It is a regulator, a contract, and a board metric." },
    ],
    approach: [
      { title: "Assess current estate", body: "OSS · BSS · network functions · customer-facing channels." },
      { title: "Stand up landing zones", body: "Telco-grade baseline · low-latency networking · evidence pipeline." },
      { title: "Migrate and modernize", body: "Strangler around OSS and BSS. Cloud-native CNFs delivered in parallel." },
      { title: "Operate as one team", body: "NOC-adjacent on-call. Runbooks that match your existing OSS." },
    ],
    diagramLabel: "OSS and BSS modernization on one side. CNF data plane on the other. Observability and SLA reporting threading both.",
    related: [
      { kind: "Solution", name: "Kubernetes", href: "/solutions/kubernetes" },
      { kind: "Solution", name: "Hybrid Cloud", href: "/solutions/hybrid_cloud" },
      { kind: "Service", name: "DevOps & Automation", href: "/services/devops_automation" },
      { kind: "Service", name: "Cybersecurity", href: "/services/cybersecurity" },
    ],
  },
};
